name: PyPI release

on: [push]

jobs:
  pypi:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Install dependencies
      run: python -m pip install --upgrade setuptools wheel twine
    - name: Build
      run: |
        python setup.py sdist bdist_wheel
        twine check dist/*
    - name: Publish package
      if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python -m pip install twine
        python -m twine upload dist/*
