
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
#from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
from tkinter import font
from PIL import Image

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1023x707")
window.configure(bg = "#2B5370")

canvas = Canvas(
    window,
    bg = "#2B5370",
    height = 707,
    width = 1023,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    928.0,
    163.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#FFFFFF",
    highlightthickness=0
)
entry_1.place(
    x=875.0,
    y=143.0,
    width=106.0,
    height=38.0
)

def round_rectangle(x1, y1, x2, y2, radius=25, **kwargs):
        
    points = [x1+radius, y1,
              x1+radius, y1,
              x2-radius, y1,
              x2-radius, y1,
              x2, y1,
              x2, y1+radius,
              x2, y1+radius,
              x2, y2-radius,
              x2, y2-radius,
              x2, y2,
              x2-radius, y2,
              x2-radius, y2,
              x1+radius, y2,
              x1+radius, y2,
              x1, y2,
              x1, y2-radius,
              x1, y2-radius,
              x1, y1+radius,
              x1, y1+radius,
              x1, y1]

    return canvas.create_polygon(points, **kwargs, smooth=True)


canvas.create_rectangle(
    603.0,
    221.0,
    630.0,
    574.0,
    fill="#C4C4C4",
    outline="")

canvas.create_rectangle(
    702.0,
    222.0,
    729.0,
    575.0,
    fill="#C4C4C4",
    outline="")

canvas.create_rectangle(
    808.0,
    222.0,
    834.0,
    575.0,
    fill="#C4C4C4",
    outline="")

canvas.create_rectangle(
    914.0,
    222.0,
    941.0,
    575.0,
    fill="#C4C4C4",
    outline="")

canvas.create_rectangle(
    898.0,
    437.0,
    957.0,
    465.0,
    fill="#FD975D",
    outline="")

canvas.create_rectangle(
    898.0,
    450.0,
    957.0,
    452.0,
    fill="#C4C4C4",
    outline="")

canvas.create_rectangle(
    58.0,
    221.0,
    165.0,
    318.0,
    fill="#C4C4C4",
    outline="")

canvas.create_rectangle(
    58.0,
    350.0,
    165.0,
    446.0,
    fill="#C4C4C4",
    outline="")

canvas.create_rectangle(
    58.0,
    477.0,
    165.0,
    574.0,
    fill="#C4C4C4",
    outline="")

canvas.create_rectangle(
    175.0,
    221.0,
    282.0,
    318.0,
    fill="#C4C4C4",
    outline="")

canvas.create_rectangle(
    175.0,
    350.0,
    282.0,
    446.0,
    fill="#C4C4C4",
    outline="")

canvas.create_rectangle(
    175.0,
    477.0,
    282.0,
    574.0,
    fill="#C4C4C4",
    outline="")

canvas.create_rectangle(
    175.0,
    477.0,
    282.0,
    574.0,
    fill="#C4C4C4",
    outline="")

canvas.create_rectangle(
    183.0,
    486.0,
    275.0,
    566.0,
    fill="#FD975D",
    outline="")

canvas.create_rectangle(
    183.0,
    230.0,
    275.0,
    311.0,
    fill="#FD975D",
    outline="")

canvas.create_rectangle(
    183.0,
    358.0,
    275.0,
    438.0,
    fill="#FD975D",
    outline="")

canvas.create_rectangle(
    66.0,
    358.0,
    158.0,
    438.0,
    fill="#FD975D",
    outline="")

canvas.create_rectangle(
    66.0,
    229.0,
    158.0,
    310.0,
    fill="#FD975D",
    outline="")

canvas.create_rectangle(
    66.0,
    485.0,
    158.0,
    565.0,
    fill="#FD975D",
    outline="")

canvas.create_rectangle(
    585.0,
    457.0,
    645.0,
    486.0,
    fill="#FD975D",
    outline="")

canvas.create_rectangle(
    585.0,
    471.0,
    645.0,
    472.0,
    fill="#C4C4C4",
    outline="")

canvas.create_rectangle(
    686.0,
    421.0,
    745.0,
    450.0,
    fill="#FD975D",
    outline="")

canvas.create_rectangle(
    686.0,
    436.0,
    745.0,
    437.0,
    fill="#C4C4C4",
    outline="")

canvas.create_rectangle(
    791.0,
    352.0,
    851.0,
    382.0,
    fill="#FD975D",
    outline="")

canvas.create_rectangle(
    791.0,
    366.0,
    851.0,
    367.0,
    fill="#C4C4C4",
    outline="")

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    943.5,
    625.0,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#FFFFFF",
    highlightthickness=0
)
entry_2.place(
    x=890.0,
    y=609.0,
    width=90.0,
    height=30.0
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    836.5,
    625.0,
    image=entry_image_3
)
entry_3 = Entry(
    bd=0,
    bg="#FFFFFF",
    highlightthickness=0
)
entry_3.place(
    x=783.0,
    y=609.0,
    width=90.0,
    height=30.0
)

entry_image_4 = PhotoImage(
    file=relative_to_assets("entry_4.png"))
entry_bg_4 = canvas.create_image(
    726.0,
    624.5,
    image=entry_image_4
)
entry_4 = Entry(
    bd=0,
    bg="#FFFFFF",
    highlightthickness=0
)
entry_4.place(
    x=680.0,
    y=609.0,
    width=90.0,
    height=29.0
)

entry_image_5 = PhotoImage(
    file=relative_to_assets("entry_5.png"))
entry_bg_5 = canvas.create_image(
    626.5,
    625.0,
    image=entry_image_5
)
entry_5 = Entry(
    bd=0,
    bg="#FFFFFF",
    highlightthickness=0
)
entry_5.place(
    x=573.0,
    y=609.0,
    width=90.0,
    height=30.0
)

button_1 = Button(
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat",
    text="Start CTRLdeck",
)

button_1['font'] = font.Font(size=24)

button_1.place(
    x=18.0,
    y=650.0,
    width=277.0,
    height=47.0
)

f13 = canvas.create_text(
    93.0,
    255.0,
    anchor="nw",
    text="F13",
    fill="#FFFFFF",
    font=("Khula Regular", 24 * -1)
)

f14 = canvas.create_text(
    210.0,
    255.0,
    anchor="nw",
    text="F14",
    fill="#FFFFFF",
    font=("Khula Regular", 24 * -1)
)

f17 = canvas.create_text(
    93.0,
    383.0,
    anchor="nw",
    text="F17",
    fill="#FFFFFF",
    font=("Khula Regular", 24 * -1)
)

f18 = canvas.create_text(
    209.0,
    383.0,
    anchor="nw",
    text="F18",
    fill="#FFFFFF",
    font=("Khula Regular", 24 * -1)
)

f21 = canvas.create_text(
    93.0,
    510.0,
    anchor="nw",
    text="F17",
    fill="#FFFFFF",
    font=("Khula Regular", 24 * -1)
)

f22 = canvas.create_text(
    210.0,
    510.0,
    anchor="nw",
    text="F22",
    fill="#FFFFFF",
    font=("Khula Regular", 24 * -1)
)

canvas.create_rectangle(
    292.0,
    222.0,
    399.0,
    319.0,
    fill="#C4C4C4",
    outline="")

canvas.create_rectangle(
    292.0,
    351.0,
    399.0,
    447.0,
    fill="#C4C4C4",
    outline="")

canvas.create_rectangle(
    292.0,
    478.0,
    399.0,
    575.0,
    fill="#C4C4C4",
    outline="")

canvas.create_rectangle(
    409.0,
    221.0,
    516.0,
    318.0,
    fill="#C4C4C4",
    outline="")

canvas.create_rectangle(
    409.0,
    350.0,
    516.0,
    446.0,
    fill="#C4C4C4",
    outline="")

canvas.create_rectangle(
    409.0,
    477.0,
    516.0,
    574.0,
    fill="#C4C4C4",
    outline="")

canvas.create_rectangle(
    409.0,
    477.0,
    516.0,
    574.0,
    fill="#C4C4C4",
    outline="")

canvas.create_rectangle(
    417.0,
    485.0,
    509.0,
    565.0,
    fill="#FD975D",
    outline="")

canvas.create_rectangle(
    417.0,
    229.0,
    509.0,
    310.0,
    fill="#FD975D",
    outline="")

canvas.create_rectangle(
    416.0,
    358.0,
    508.0,
    438.0,
    fill="#FD975D",
    outline="")

canvas.create_rectangle(
    300.0,
    358.0,
    392.0,
    438.0,
    fill="#FD975D",
    outline="")

canvas.create_rectangle(
    300.0,
    230.0,
    392.0,
    311.0,
    fill="#FD975D",
    outline="")

canvas.create_rectangle(
    300.0,
    486.0,
    392.0,
    566.0,
    fill="#FD975D",
    outline="")

f15 = canvas.create_text(
    327.0,
    255.0,
    anchor="nw",
    text="F15",
    fill="#FFFFFF",
    font=("Khula Regular", 24 * -1)
)

f16 = canvas.create_text(
    446.0,
    254.0,
    anchor="nw",
    text="F16",
    fill="#FFFFFF",
    font=("Khula Regular", 24 * -1)
)

f19 = canvas.create_text(
    327.0,
    383.0,
    anchor="nw",
    text="F19",
    fill="#FFFFFF",
    font=("Khula Regular", 24 * -1)
)

f20 = canvas.create_text(
    446.0,
    381.0,
    anchor="nw",
    text="F20",
    fill="#FFFFFF",
    font=("Khula Regular", 24 * -1)
)

f23 = canvas.create_text(
    327.0,
    510.0,
    anchor="nw",
    text="F23",
    fill="#FFFFFF",
    font=("Khula Regular", 24 * -1)
)

port_label = canvas.create_text(
    783.0,
    138.0,
    anchor="nw",
    text="Port:",
    fill="#FFFFFF",
    font=("Khula Regular", 36 * -1)
)

outline1 = round_rectangle(
    12.0,
    187.0,
    1003.0,
    609.0,
    fill="",
    radius=20,
    outline="#FD975D")

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    365.0,
    99.0,
    image=image_image_1
)
window.resizable(False, False)
window.mainloop()
